## Introduction to Python

## Basic Jupyter

mark down text line

In [99]:
#code line
print("hello world")

hello world


In [100]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [101]:
###use show contextual help
print("hello world")

hello world


## Basic python

### basic operations

In [102]:
a = 3

In [103]:
a

3

In [104]:
b =2

In [105]:
a**b

9

In [106]:
a*b

6

In [107]:
c = a**b
d = a*b

In [108]:
print(a,'square is', c)
print(a,'multiply by',b, "is",d )

3 square is 9
3 multiply by 2 is 6


In [109]:
5//4

1

In [110]:
5/4

1.25

In [111]:
int(5/4)

1

In [112]:
5.5//4

1.0

In [113]:
7%4

3

In [114]:
a = list([1,[2,3]])

In [115]:
a

[1, [2, 3]]

In [116]:
len(a)

2

In [117]:
b = dict([('x', 5), ('y', -5)])

In [118]:
b

{'x': 5, 'y': -5}

### conditional statements

In [119]:
a = 3
b = 2

In [120]:
if (a > 3):
    e = a
elif (a < 3):
    e = 3
else:
    e = 0

In [121]:
e

0

In [122]:
if (a > 3) or (b <=2):
    e = a + b

In [123]:
e

5

Other conditional statements include switch/case pairs and won't be discussed here since we won't use it for this course.

### loop statements

In [124]:
a = 0

In [125]:
for i in range(0,10):
    a = a + i

In [126]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [127]:
a

45

In [128]:
b = 0

In [129]:
i = 0
while i < 10:
    b = b + i
    i = i +1

In [130]:
b

45

### define a function

In [131]:
def combine_two(a,b):
    c = a + b
    return c

In [132]:
c=combine_two(10.5,8)

In [133]:
c

18.5

In [134]:
c =combine_two(a,b)

In [135]:
c

90

#### Task
Write a function (gisc_exponential) to calculate the exponential of a variable with the base of Euler’s number. Return 0 if the result is smaller than 0.1.

In [136]:
from math import exp as e

In [137]:
def gisc_exponential(X):
    """
    Var X: int
    Return:
        exponential of a variable with the base of Euler’s number
        Return 0 if the result is smaller than 0.1
    """
    X = exp(X)
    if X < 0.1:
        return 0
    else:
        return X

In [138]:
from math import e
def gisc_exponential(X):
    return 0 if e**X<0.1 else e**X

In [139]:
print(gisc_exponential(1))

2.718281828459045


In [140]:
len("ifrom math import edef gisc_exponential(X):return 0 if e**X<0.1 else e**X")

73

## Matrix manipulate
Numpy is "The fundamental package for scientific computing with Python". (https://numpy.org)

#### importing libraries

Libraries are existing packages of functions/classes written by you or someone else. You can utilize the existing functions to speed up your work.

In [141]:
import numpy as np

In [142]:
from numpy import sqrt as npsqrt

In [143]:
np.sqrt(10)

3.1622776601683795

In [144]:
npsqrt(10)

3.1622776601683795

#### create a matrix

In [145]:
a = np.arange(0,1000,1)

In [146]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [147]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481,
        5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189,
        5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ,
        6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958,
        6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ,
        7.07106781,  7.14142843,  7.21110255,  7.28010989,  7.34846923,
        7.41619849,  7.48331477,  7.54983444,  7.61577311,  7.68114575,
        7.74596669,  7.81024968,  7.87400787,  7.93725393,  8.        ,
        8.06225775,  8.1240384 ,  8.18535277,  8.24621125,  8.30

In [148]:
a.shape

(1000,)

In [149]:
b=np.reshape(a,(10,-1))

In [150]:
b.shape

(10, 100)

In [151]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
        165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 17

In [152]:
c = np.zeros((10,100))

In [153]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

#### matrix calculation

In [154]:
d = np.arange(0.0, 1000.0, 1.0).reshape(10,-1)

In [155]:
d.shape

(10, 100)

In [156]:
d

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
         66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
         77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
         88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
         99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
        122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
        133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
        144., 145., 146

In [157]:
d.dtype

dtype('float64')

In [158]:
b.dtype

dtype('int64')

In [159]:
np.multiply(b,d)

array([[0.00000e+00, 1.00000e+00, 4.00000e+00, 9.00000e+00, 1.60000e+01,
        2.50000e+01, 3.60000e+01, 4.90000e+01, 6.40000e+01, 8.10000e+01,
        1.00000e+02, 1.21000e+02, 1.44000e+02, 1.69000e+02, 1.96000e+02,
        2.25000e+02, 2.56000e+02, 2.89000e+02, 3.24000e+02, 3.61000e+02,
        4.00000e+02, 4.41000e+02, 4.84000e+02, 5.29000e+02, 5.76000e+02,
        6.25000e+02, 6.76000e+02, 7.29000e+02, 7.84000e+02, 8.41000e+02,
        9.00000e+02, 9.61000e+02, 1.02400e+03, 1.08900e+03, 1.15600e+03,
        1.22500e+03, 1.29600e+03, 1.36900e+03, 1.44400e+03, 1.52100e+03,
        1.60000e+03, 1.68100e+03, 1.76400e+03, 1.84900e+03, 1.93600e+03,
        2.02500e+03, 2.11600e+03, 2.20900e+03, 2.30400e+03, 2.40100e+03,
        2.50000e+03, 2.60100e+03, 2.70400e+03, 2.80900e+03, 2.91600e+03,
        3.02500e+03, 3.13600e+03, 3.24900e+03, 3.36400e+03, 3.48100e+03,
        3.60000e+03, 3.72100e+03, 3.84400e+03, 3.96900e+03, 4.09600e+03,
        4.22500e+03, 4.35600e+03, 4.48900e+03, 4.62

In [160]:
b*d

array([[0.00000e+00, 1.00000e+00, 4.00000e+00, 9.00000e+00, 1.60000e+01,
        2.50000e+01, 3.60000e+01, 4.90000e+01, 6.40000e+01, 8.10000e+01,
        1.00000e+02, 1.21000e+02, 1.44000e+02, 1.69000e+02, 1.96000e+02,
        2.25000e+02, 2.56000e+02, 2.89000e+02, 3.24000e+02, 3.61000e+02,
        4.00000e+02, 4.41000e+02, 4.84000e+02, 5.29000e+02, 5.76000e+02,
        6.25000e+02, 6.76000e+02, 7.29000e+02, 7.84000e+02, 8.41000e+02,
        9.00000e+02, 9.61000e+02, 1.02400e+03, 1.08900e+03, 1.15600e+03,
        1.22500e+03, 1.29600e+03, 1.36900e+03, 1.44400e+03, 1.52100e+03,
        1.60000e+03, 1.68100e+03, 1.76400e+03, 1.84900e+03, 1.93600e+03,
        2.02500e+03, 2.11600e+03, 2.20900e+03, 2.30400e+03, 2.40100e+03,
        2.50000e+03, 2.60100e+03, 2.70400e+03, 2.80900e+03, 2.91600e+03,
        3.02500e+03, 3.13600e+03, 3.24900e+03, 3.36400e+03, 3.48100e+03,
        3.60000e+03, 3.72100e+03, 3.84400e+03, 3.96900e+03, 4.09600e+03,
        4.22500e+03, 4.35600e+03, 4.48900e+03, 4.62

In [161]:
np.matmul(b,d.transpose())

array([[  328350.,   823350.,  1318350.,  1813350.,  2308350.,  2803350.,
         3298350.,  3793350.,  4288350.,  4783350.],
       [  823350.,  2318350.,  3813350.,  5308350.,  6803350.,  8298350.,
         9793350., 11288350., 12783350., 14278350.],
       [ 1318350.,  3813350.,  6308350.,  8803350., 11298350., 13793350.,
        16288350., 18783350., 21278350., 23773350.],
       [ 1813350.,  5308350.,  8803350., 12298350., 15793350., 19288350.,
        22783350., 26278350., 29773350., 33268350.],
       [ 2308350.,  6803350., 11298350., 15793350., 20288350., 24783350.,
        29278350., 33773350., 38268350., 42763350.],
       [ 2803350.,  8298350., 13793350., 19288350., 24783350., 30278350.,
        35773350., 41268350., 46763350., 52258350.],
       [ 3298350.,  9793350., 16288350., 22783350., 29278350., 35773350.,
        42268350., 48763350., 55258350., 61753350.],
       [ 3793350., 11288350., 18783350., 26278350., 33773350., 41268350.,
        48763350., 56258350., 6375335

#### Task2
Try to use the function you wrote (gisc_exponential) from the above with the numpy array (b), will it work?
Rewrite the function using numpy function np.exp.

In [ ]:
# from math import e
# def gisc_exponential(X):
#     return 0 if e**X<0.1 else e**X

In [192]:
# array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
#          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
#          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
#          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
#          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
#          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
#          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
#          91,  92,  93,  94,  95,  96,  97,  98,  99],

In [197]:
result = np.where(e**b < 10, 0, e**b)
result

/tmp/ipykernel_471903/4048465731.py:1: RuntimeWarning: overflow encountered in power
  result = np.where(e**b < 10, 0, e**b)


array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.00855369e+001, 5.45981500e+001, 1.48413159e+002,
        4.03428793e+002, 1.09663316e+003, 2.98095799e+003,
        8.10308393e+003, 2.20264658e+004, 5.98741417e+004,
        1.62754791e+005, 4.42413392e+005, 1.20260428e+006,
        3.26901737e+006, 8.88611052e+006, 2.41549528e+007,
        6.56599691e+007, 1.78482301e+008, 4.85165195e+008,
        1.31881573e+009, 3.58491285e+009, 9.74480345e+009,
        2.64891221e+010, 7.20048993e+010, 1.95729609e+011,
        5.32048241e+011, 1.44625706e+012, 3.93133430e+012,
        1.06864746e+013, 2.90488497e+013, 7.89629602e+013,
        2.14643580e+014, 5.83461743e+014, 1.58601345e+015,
        4.31123155e+015, 1.17191424e+016, 3.18559318e+016,
        8.65934004e+016, 2.35385267e+017, 6.39843494e+017,
        1.73927494e+018, 4.72783947e+018, 1.28516001e+019,
        3.49342711e+019, 9.49611942e+019, 2.58131289e+020,
        7.01673591e+020, 1.90734657e+021, 5.18470553e+02

array([[1.00000000e+000, 2.71828183e+000, 7.38905610e+000,
        2.00855369e+001, 5.45981500e+001, 1.48413159e+002,
        4.03428793e+002, 1.09663316e+003, 2.98095799e+003,
        8.10308393e+003, 2.20264658e+004, 5.98741417e+004,
        1.62754791e+005, 4.42413392e+005, 1.20260428e+006,
        3.26901737e+006, 8.88611052e+006, 2.41549528e+007,
        6.56599691e+007, 1.78482301e+008, 4.85165195e+008,
        1.31881573e+009, 3.58491285e+009, 9.74480345e+009,
        2.64891221e+010, 7.20048993e+010, 1.95729609e+011,
        5.32048241e+011, 1.44625706e+012, 3.93133430e+012,
        1.06864746e+013, 2.90488497e+013, 7.89629602e+013,
        2.14643580e+014, 5.83461743e+014, 1.58601345e+015,
        4.31123155e+015, 1.17191424e+016, 3.18559318e+016,
        8.65934004e+016, 2.35385267e+017, 6.39843494e+017,
        1.73927494e+018, 4.72783947e+018, 1.28516001e+019,
        3.49342711e+019, 9.49611942e+019, 2.58131289e+020,
        7.01673591e+020, 1.90734657e+021, 5.18470553e+02

In [164]:
gisc = np.vectorize(gisc_exponential)

In [ ]:
result = np.array([gisc_exponential(xi) for xi in b]).all()